"""Add Lottoschein to Database

Revision ID: 00b6530c46fd
Revises: 
Create Date: 2024-11-09 16:13:09.143359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b6530c46fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lottoscheine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lottozahl1', sa.Integer(), nullable=False),
    sa.Column('lottozahl2', sa.Integer(), nullable=False),
    sa.Column('lottozahl3', sa.Integer(), nullable=False),
    sa.Column('lottozahl4', sa.Integer(), nullable=False),
    sa.Column('lottozahl5', sa.Integer(), nullable=False),
    sa.Column('lottozahl6', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lottoscheine')
    # ### end Alembic commands ###
