"""Add Lottoschein-Examples to Database

Revision ID: 53d4df936243
Revises: 00b6530c46fd
Create Date: 2024-11-12 15:11:24.235306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d4df936243'
down_revision = '00b6530c46fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lottoscheine_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lottozahl1', sa.Integer(), nullable=False),
    sa.Column('lottozahl2', sa.Integer(), nullable=False),
    sa.Column('lottozahl3', sa.Integer(), nullable=False),
    sa.Column('lottozahl4', sa.Integer(), nullable=False),
    sa.Column('lottozahl5', sa.Integer(), nullable=False),
    sa.Column('lottozahl6', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lottoscheine_examples')
    # ### end Alembic commands ###
