"""Add LottoHistoric table

Revision ID: e22c2a7ee8e8
Revises: 53d4df936243
Create Date: 2024-11-25 16:41:37.231863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22c2a7ee8e8'
down_revision = '53d4df936243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotto_historic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ziehungsdatum', sa.Date(), nullable=False),
    sa.Column('lottozahl1', sa.Integer(), nullable=False),
    sa.Column('lottozahl2', sa.Integer(), nullable=False),
    sa.Column('lottozahl3', sa.Integer(), nullable=False),
    sa.Column('lottozahl4', sa.Integer(), nullable=False),
    sa.Column('lottozahl5', sa.Integer(), nullable=False),
    sa.Column('lottozahl6', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lotto_historic')
    # ### end Alembic commands ###
